name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "sean.m.mcquaid@gmail.com"
        git config --global user.name "sean.mcquaid"
        git remote set-url origin ${{ secrets.GITHUB_TOKEN }}@github.com/sean.mcquaid/${{ github.repository }}>.git
        npm run deploy